name: Generate Futuristic Dev Animation

on:
  schedule: # Runs every day
    - cron: "0 0 * * *"

  workflow_dispatch: # Allow manual triggering

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate futuristic dev grid
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/dev-grid.svg?palette=github-dark

      - name: Push futuristic grid to profile
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Display preview in logs
        run: cat dist/dev-grid.svg

