name: Generate Project Bubbles

on:
  schedule: # Runs every day
    - cron: "0 0 * * *"

  workflow_dispatch: # Allow manual triggering

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch public repositories
        id: get_repos
        run: |
          curl -s https://api.github.com/users/${{ github.repository_owner }}/repos?per_page=100 \
          | jq -r '.[] | select(.private == false) | .name' > repos.txt

      - name: Generate bubble animation
        run: |
          mkdir -p dist
          repos=$(cat repos.txt | tr '\n' ' ')
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="800" height="400" viewBox="0 0 800 400">
          <defs>
            <style>
              .bubble { fill: #ffd700; opacity: 0.85; animation: float 6s infinite ease-in-out alternate; }
              .text { fill: #000; font-family: Arial, sans-serif; font-size: 12px; font-weight: bold; text-anchor: middle; dominant-baseline: middle; }
              @keyframes float {
                0% { transform: translateY(0); }
                100% { transform: translateY(-10px); }
              }
            </style>
          </defs>
          <rect width="100%" height="100%" fill="#1e1e1e"/>
          <g>' > dist/project-bubbles.svg
          
          x=100 y=100 radius=40
          for repo in $repos; do
            echo "<circle class='bubble' cx='$x' cy='$y' r='$radius' />
            <text class='text' x='$x' y='$y'>$repo</text>" >> dist/project-bubbles.svg
            x=$((x+150))
            [ $x -gt 700 ] && x=100 && y=$((y+100))
          done
          
          echo '</g></svg>' >> dist/project-bubbles.svg

      - name: Push bubble animation to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Display preview in logs
        run: cat dist/project-bubbles.svg
