name: Generate Futuristic Dev Animation Grid

on:
  schedule: # Runs every day
    - cron: "0 0 * * *"

  workflow_dispatch: # Allow manual triggering

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate futuristic grid animation
        run: |
          mkdir -p dist
          echo '<svg xmlns="http://www.w3.org/2000/svg" width="800" height="400" viewBox="0 0 800 400">
          <defs>
            <style>
              .grid { fill: none; stroke: #ffd700; stroke-width: 0.5; }
              .glow { fill: #00ffff; opacity: 0.7; animation: pulse 2s infinite alternate; }
              @keyframes pulse {
                0% { opacity: 0.5; }
                100% { opacity: 1; }
              }
            </style>
          </defs>
          <rect class="grid" width="100%" height="100%" />
          <circle class="glow" cx="200" cy="100" r="30"/>
          <circle class="glow" cx="400" cy="200" r="50"/>
          <circle class="glow" cx="600" cy="300" r="40"/>
          <text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" fill="#fff" font-size="24" font-family="Arial">
            Game Dev Grid
          </text>
          </svg>' > dist/dev-grid.svg

      - name: Push futuristic animation to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Display preview in logs
        run: cat dist/dev-grid.svg
